name: Flutter Compile Release
on:
  push:
    branches:
      - main  # Specify the branches to watch
    tags:
      - "*"  # Keep this to trigger on tag pushes as well

jobs: 
  windows:
    runs-on: windows-latest
    steps:
      - name: Install yq
        run: choco install yq

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Create Flutter project
        run: flutter create .

      - name: Build Windows release
        run: flutter build windows --release

      - name: Install zip utility
        run: choco install zip
        shell: powershell

      - name: Archive release
        run: |
          mkdir -p build/windows/x64/runner/Release
          cd build/windows/x64/runner/Release
          zip -r windows.zip .
        shell: bash

      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build/windows/x64/runner/Release/windows.zip