name: Flutter Compile Release
on: workflow_dispatch




# steps:
#   - name: Clone repository
#     uses: actions/checkout@v4
#   - name: Set up Flutter
#     uses: subosito/flutter-action@v2
#     with:
#       channel: stable
#       flutter-version-file: pubspec.yaml # path to pubspec.yaml
#   - run: flutter --version

jobs: 
  
 windows:
    runs-on: windows-latest
    steps:
      - run: winget install --id MikeFarah.yq
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter config --enable-windows-desktop
      - run: flutter create .
      - run: flutter build windows
      - uses: actions/upload-artifact@master
        with:
          name: windows
          path: build\windows\runner\Release