name: Flutter Compile Release
on: workflow_dispatch




# steps:
#   - name: Clone repository
#     uses: actions/checkout@v4
#   - name: Set up Flutter
#     uses: subosito/flutter-action@v2
#     with:
#       channel: stable
#       flutter-version-file: pubspec.yaml # path to pubspec.yaml
#   - run: flutter --version

jobs: 
  
 windows:
    runs-on: windows-latest
    steps:
      - run: choco install yq

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - run: flutter config --enable-windows-desktop
      - run: flutter create .
      - run: flutter build windows --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'windows.zip'
          directory: build\windows\x64\runner\Release
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: build\windows\x64\runner\Release\windows.zip