name: Flutter Compile Release
on: 
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs: 
  windows:
    runs-on: windows-latest
    steps:
      - name: Install yq
        run: choco install yq

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Create Flutter project
        run: flutter create .

      - name: Build Windows release
        run: flutter build windows --release

      - name: Install Inno Setup
        run: choco install innosetup
        shell: powershell

      - name: Extract Version from Tag
        id: get_version
        run: echo "##[set-output name=VERSION;]${GITHUB_REF#refs/tags/}"
      
      - name: Create Inno Setup Script
        run: |
          Add-Content -Path "installer.iss" -Value "[Setup]"
          Add-Content -Path "installer.iss" -Value "AppName=Anomaly"
          Add-Content -Path "installer.iss" -Value "AppVersion=${{ steps.get_version.outputs.VERSION }}"
          Add-Content -Path "installer.iss" -Value "DefaultDirName={pf}\Anomaly"
          Add-Content -Path "installer.iss" -Value "DefaultGroupName=Anomaly"
          Add-Content -Path "installer.iss" -Value "OutputBaseFilename=installer"
          Add-Content -Path "installer.iss" -Value "Compression=lzma"
          Add-Content -Path "installer.iss" -Value "SolidCompression=yes"
          Add-Content -Path "installer.iss" -Value "[Files]"
          Add-Content -Path "installer.iss" -Value "Source: ""build\\windows\\x64\\runner\\Release\\*""; DestDir: ""{app}""; Flags: ignoreversion recursesubdirs createallsubdirs"
          Add-Content -Path "installer.iss" -Value "[Icons]"
          Add-Content -Path "installer.iss" -Value "Name: ""{group}\Anomaly""; Filename: ""{app}\anomaly.exe"""

      - name: Build the Installer
        run: "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe installer.iss"

      - name: Upload installer to GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: installer.exe